version: "3.3"
services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres
    env_file:
      - .env
    volumes:
      - ./pv/pgdata/:/opt/pgsql/data
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"
  celery_worker:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./pv/:/pv/
    ports:
      - "8888:8888"
    #command: celery -A mysite worker --loglevel=info
    #command: ['celery', 'worker', '-A', 'app.app', '-l', 'info']
    entrypoint: celery -A celery_worker.tasks worker --loglevel=info
    depends_on:
      - redis
  celery_monitor:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./pv/:/pv/
    ports:
      - "5555:5555"
    entrypoint: celery -A celery_worker.tasks flower --port=5555 --broker=redis://redis:6379/0
    #command: celery -A tasks flower --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis
